AWSTemplateFormatVersion: "2010-09-09"
Description: AWS AppSync Journal API

Parameters:
  APIName:
    Type: String
    Description: Name of the API
    MinLength: 3
    MaxLength: 20
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9_]*$

Resources:
  EntryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${APIName}EntryTable
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Name
          Value: !Sub ${APIName}EntryTable

  TagTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${APIName}TagTable
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
        -
          AttributeName: parentId
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
        -
          AttributeName: parentId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Name
          Value: !Sub ${APIName}TagTable

  DynamoDBPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed policy to allow AppSync to access DynamoDB tables.
      Path: /appsync/
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
            Resource:
            - !Join [ "", [ !GetAtt EntryTable.Arn, "*" ] ]
            - !Join [ "", [ !GetAtt TagTable.Arn, "*" ] ]

  DynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${APIName}-appsync-dynamodb-role
      ManagedPolicyArns:
        - Ref: DynamoDBPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com
    DependsOn:
      - DynamoDBPolicy

Outputs:
  EntryTableName:
    Description: The name of the Entry table
    Value: !Ref EntryTable
  TagTableName:
    Description: The name of the Tag table
    Value: !Ref TagTable