AWSTemplateFormatVersion: "2010-09-09"
Description: AWS AppSync Journal API

Parameters:
  APIName:
    Type: String
    Description: Name of the API
    MinLength: 3
    MaxLength: 20
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9_]*$

Resources:
  EntryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${APIName}EntryTable
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

  TagTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${APIName}TagTable
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
        -
          AttributeName: parentId
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
        -
          AttributeName: parentId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

Outputs:
  EntryTableName:
    Description: The name of the Entry table
    Value: !Ref EntryTable