mutation addEntry {
  createEntry(input: {
    # content: [{
    #   type: "P"
    #   content: "Testing"
    # }],
    content: "[1, 2, 3]",
    tags: ["work"],
    title: "Some title"
  }) {
    id
    content
    tags
    title
  }
}

query getEntries {
  listEntries {
    items {
      id
      title
      content
    }
  }
}
